#!/usr/bin/python
"""
Script to generate the configuration files for the replay of AGATA data using the
multi-process distributed system Narval or the single-process emulator femul.
The script is divided in a few sections, some of which are specific to the actual
analysis (and therefore are likely to be changed by the user) while some others are
normally not to be touched:
0) Type of analysis and replacement macros (in the style of the shell) used to parametrize
   the commands listed in 2).
1) The structure of the actual analysis is defined by the variables PROGTYPE and CONFTYPE and
   by the dictionaries Topology and Actors. The dictionary ExtraFiles contains a list of files,
   which are needed by the analysis but are not generated by this script (e.g. calibrations,
   mappings, ...); these files can be copied from a previous analysis if the script is started
   WITH the option -o or --old (python gen_conf.py -h to get the list of accepted options)
2) The command lines to be written in the conf files of the actors defined in Actors{}.
   Uncomment/comment/modify the command lines and their parameters
3) A small database defining the position and the PSA signal basis of the germanium crystals.
   This part should not need to be changed.  

To get a list of command line arguments, launch it as "gen_conf.py -h"

This script is (tentativelly) updated to follow the new naming of crystals

"""

import os

#With the information reported in 1) and 2) it should be rather strightforward to produce the
#topology file xxxxx.xml for narval (or xxxx.conf for femul) and the xxxx script for narval.

###############################################################################################
###################  0  Type of analysis and replacement symbols  #############################
###############################################################################################

PROGTYPE='femul'     # NARVAL or femul   (to choose between os.getcwd() and '' for CWD)
CONFTYPE='OFFLINE'    # ONLINE or OFFLINE (used just to exclude the ReadDataDir line in the Producers)

MACROS={              # various replacements for symbols defined in 2).
'$CONFDIR'      : 'Conf',                      # this will be prefixed by CWD/
'$READDIR'      : 'Data',                      # this will be prefixed by CWD/; if ONLINE this will not be written
'$SAVEDIR'      : 'Out',                       # this will be prefixed by CWD/; if ONLINE this will be replaced by $READDIR
'$ANALYSIS'     : 'Analysis',                  # this will be prefixed by CWD/; if ONLINE this will be replaced by $READDIR
'$BUILDER'      : 'Builder',                   # this will be prefixed by CWD/
'$MERGER'       : 'Merger',                    # this will be prefixed by CWD/
'$VAMOS'        : 'vamos',                      # this will be prefixed by CWD/
#'$NEDA'         : 'neda',                      # this will be prefixed by CWD/
#'$DIAMANT'      : 'diamant',                   # this will be prefixed by CWD/
#'$BUILDNEDA'    : 'BuildNeda',                # this will be prefixed by CWD/
#'$BUILDDIAMANT' : 'BuildDiamant',              # this will be prefixed by CWD/
'$GLOBAL'       : 'Global',                    # this will be prefixed by CWD/
'$PSABASE'      : '/agatadisks1/marcosic/PSA_bases',             # standard place at AGATA
'$CRYSTAL_ID'   : "",                          # the actual value is defined in GeDataBase
'$SIGNAL_BASIS' : "",                          # the actual value is defined in GeDataBase
'$CRYSTAL'      : "",                          # the actual value taken from Topology['CRYSTAL']
}

###############################################################################################
###################  1  Structure of analysis  ################################################
###############################################################################################

Topology={    # The directories to be generated in Conf, Data and Out
'CRYSTAL'      : "00A 00B 00C 01A 01B 01C 02A 02B 02C 03A 03B 03C 04A 04B 04C 05A 05B 05C 06A 06B 06C 07A 07B 07C 09B 09C 10A 10B 10C 11A 11B 11C 12A 12B 12C 13A 13B 13C 14A 14B 14C",
'BUILDER'      : "Builder",
'MERGER'       : "Merger",
'VAMOS'        : "vamos",
#'NEDA'         : "neda",
#'DIAMANT'      : "diamant",
#'BUILDNEDA'    : "BuildNeda",
#'BUILDDIAMANT' : "BuildDiamant",
'GLOBAL'     : "Global",
'ANALYSIS'     : "Analysis",
}

# The name of the used actors must correspond to one of the tuples defined in the following section.
# This requirement creates a problem for BasicAFP and BasicAFC when they are used in chains of different type
# (e.g. after PSA and after Tracking) and one wants to define chain-specific names for their input/output files.
# The solution is to suffix the name of the chain-type (e.g. _CRYSTAL or _GLOBAL or any other), to the defining tuple. 
# This suffix will be silently removed from the actual name of the generated configuration files.

Actors={      # These are the xxxx.conf files to be generated 
'CRYSTAL'      : "CrystalProducer PreprocessingFilter PSAFilter BasicAFC BasicAFP_CRYSTAL PostPSAFilter PostPSAFilter ProdHist PSAHist PreproHist",
'VAMOS'        : "BasicAFP_VAMOS BasicAFC_VAMOS BasicMFMP", 
#'NEDA'         : "BasicAFP_NEDA BasicAFC_NEDA BasicATSB_NEDA", 
#'DIAMANT'      : "BasicAFP_DIAMANT BasicAFC_DIAMANT BasicATSB_DIAMANT",
#'BUILDNEDA'    : "BasicAFP_BUILDNEDA", 
#'BUILDDIAMANT' : "BasicAFP_BUILDDIAMANT",
'BUILDER'      : "EventBuilder BasicAFC_BUILDER TrackingFilter BasicAFP_BUILDER TreeBuilder",
'MERGER'       : "EventMerger_MERGER BasicAFC_MERGER TrackingFilter TreeBuilder TB_VAMOS", 
'GLOBAL'    : "EventBuilder BasicAFC_GLOBAL TrackingFilter", 
}

ExtraFiles={  # If not already present, these files can be copied from a directory specified in the command line. CrystalPos LUT is placed at 3 places in order to have eventually tracking at different places offline
'CRYSTAL'   : "CrystalProducerATCA.conf PreprocessingFilterPSA.conf xinv_1325-1340.cal xdir_1325-1340.cal Trapping.cal RecalEnergy2.cal", #Trapping_$CRYSTAL.cal recal2.dat <== files for n damage correction, not used at the moment
'GLOBAL'    : "CrystalPositionLookUpTable",
#'MERGER'    : "CrystalPositionLookUpTable neda_id_lookup diamant_id_lookup",
'MERGER'    : "CrystalPositionLookUpTable",
'BUILDER'   : "CrystalPositionLookUpTable",
}

###############################################################################################
###################  2  Tuples specifying the content of the configuration files  #############
###############################################################################################

#########################

CrystalProducer=(
"ActualClass           CrystalProducerATCA",     # name of the used daugther class  
"CrystalID             $CRYSTAL_ID",             # position of the crystal in the AGATA frame
"ReadDataDir           $READDIR/$CRYSTAL",       # should not be present in the ONLINE producer, automatically done when flag "online is active"
"SaveDataDir           $SAVEDIR/$CRYSTAL",       # Out/04C... for the OFFLINE; Data/04C... for the online
"TraceLength           100",                     # length of traces (samples)
"WriteDataMask         0",                       # 0=none 1=input_mezzdata 2=event_mezzdata 4=event_mezzhead 8=event_energy 16=event_core 32=tstampdiff; 10=8+2
"WriteTraces           100",                     # number of traces written to "Prod__1000-42-100-S__Traces.samp" at the beginning of the run
# to be uncommented for offline starting from traces !!!
"InputDataFile         event_mezzdata.cdat",     # modify definitions in the online version of CrystalProducerATCA.conf to read from a single raw-data file
#"InputDataFile         arg__4120-UA__.dat",     # modify definitions in the online version of CrystalProducerATCA.conf to read from a single raw-data file
"AllInputFiles",                                 # filename.ext --> filename.ext.0000 and increment the string after last . 
#"WriteBaseLines        10",                     # distribution of preamplifier baselines; events decimated by 10
#"DecimateMezzdata     4",                       # write one out of 4 (if WriteDataMask enables)
#"DecimateMezzener     2",                       # write one out of 2 (if WriteDataMask enables)
#"TimeStep              50",                     # not needed since the online has now a dedicated watchdog
#"TstampCorrection      0",                      # used in the offline to correct for rare cases of bad setup
#"MaxTstampSeconds      3200",                   #
#"WriteDataSplit        1000000",                # Size of event_mezzdata.cdat.xxxx is ~4GB (.cdat as data is compressed) 
#"WriteCompressed",                              # WriteCompressed is the default
#"WriteUnCompressed",                            # to get uncompressed raw data
#Co60 mainly...
#"WriteDataRange        1500 25000",              # range of CC amplitude (in channels) to write the data, not given means write all  
#"StopErrorCode         100",                     # < 100 to avoid stopping everything at the first input error
#"ValidationRate        2000",                    # readout event-rate. Used to reduce the buffer size in the online ACQ so as to gent ~1 read/second
#"NoMultiHist",                                   # exclude local spectra and matrices
"ProjeM1               10 2",                    # threshold (rescaled) and scaling factor for segment multiplicity=1 projections, calibration pourpose mainly...
#"Verbose",                                       # more verbose terminal-output
#### command lines to be produced only for the specified crystals
{
#'1B' : "WriteDataRange  5500 20000",
#'11C': "TstampCorrection      -112",                      
#'20A': "TstampCorrection      60",                      
#'20B': "TstampCorrection      60",                      
}
)

#########################

PreprocessingFilter=(
"ActualClass           PreprocessingFilterPSA",  # name of the used daugther class  
"SaveDataDir           $SAVEDIR/$CRYSTAL",       # normally Out/1R...
"EnergyGain            4",                       # channels/keV of the calibrated energy spectra
"XtalkFile             xinv_1325-1340.cal",      # cross talk correction coefficients for the energies
"WriteTraces           100" ,                    # number of traces written to "Prep__1000-42-100-S__Traces.samp" at the beginning of the run
#"SegmentFoldGate       1 3",                    # selection of events based on the number of hit segments
#"SegmentEnergyThreshold  f32",                  # minimum energy on the segments to decide if fired, 10 keV is the default, look to Pre*PSA.conf file
"PileUpCheck             0 0",              # Slope Delta (no check if <= 0; default is to check)
#"CFDparamsCC             i32 i32 i32 f32 f32",  # Int Diff Delay Fraction Threshold
#"TriggerWithCoreAlone    bool",                 # don't use net_charge_segments to find local trigger
#"CoreEnergyGate        500 10000",              # possibility to restrict the energy range
#"RisetimeMatrix          bool",                 #produce risetime matrix for segments and core
#"NoMultiHist",                                  # exclude local spectra and matrices
#"Verbose",                                      # more verbose terminal-output
#### command lines to be produced only for the specified crystals
{
'01A' : ("DeadSegment    24 0.93773  0."),
'07A' : ("DeadSegment    8  0.941088 0."),
'07B' : ("DeadSegment    35 0.940338 0."),
'11A' : ("DeadSegment    18 0.947    0."),
'14B' : ("DeadSegment    34 0.942589 0."),
}
)

#########################

PSAFilter=(
"ActualClass           PSAFilterGridSearch",      # name of the used daugther class  
"BasisFile             $SIGNAL_BASIS",            # this is generated from the GeDataBase structure (see at line ~230 of this file)  
"SaveDataDir           $SAVEDIR/$CRYSTAL",        # normally Out/Data(online)
"EnergyGain            4",                        # channels/keV of the calibrated energy spectra
"XtalkFile             xdir_1325-1340.cal",       # cross talk correction coefficients for traces (applied to the signal basis)
"Threads               5 300",                    # number of threads, number of events/thread (if PSA threads enabled at compile time)
"GridSearchType        Adaptive",                 # SegCenter, Adaptive, CoarseOnly or Full; default is Adaptive
#"GridSearchType        SegCenter",                # SegCenter, Adaptive, CoarseOnly or Full; default is Adaptive
#"WriteTraces           500",                      # number of traces+fit written to "Prep__1000-42-100-S__Traces.samp" at the beginning of the run
#"GridSearchType        SegCenter",               # SegCenter, Adaptive, CoarseOnly or Full; default is Adaptive
#"TauSlice              35 35 35 35 35 35 35",    # preamp response of the 6 slices and the CC
#"TZeroCycles           10",                      # max number of PSA+FitTZero cycles
#"TauSegment       i32 f32",                      # segment number, its timing response (can be given multiple times, 36==CC)
#"TauDecay         f32",                          # fall time in ns of the preamplifiers (default is not to correct basis for this) 
#"Smooth           f32",                          # final gaussian smoothing of the signal basis (0==no, default is 0.1)
#"WritePsaHits",                                  # writes the hits in binary to calibrate neutron damage
#"NoMultiHist",                                   # exclude local spectra and matrices
#"Verbose",                                       # more verbose terminal-output
#### command lines to be produced only for the specified crystals
{
'01A' : ("DeadSegment    24"),
'07A' : ("DeadSegment     8"),
'07B' : ("DeadSegment    35"),
'11A' : ("DeadSegment    18"),
'14B' : ("DeadSegment    34"),
}
)

PostPSAFilter=(
"ActualClass           PostPSAFilter",           # name of the used daugther class, uncomment for offline 
"SaveDataDir           $SAVEDIR/$CRYSTAL",       # normally Out
"EnergyGain            4",                       # channels/keV of the calibrated energy spectra
#"SmearPos              4",                       # to randomize points on a 2mm3 volume
#"ForceSegmentsToCore",                           # sum of segments forced to energy of the core. Use it EITHER in the PSA OR in the Tracking
#"CoreEnergyGate        500 520 ",               # possibility to restrict the energy range
#"RecalCC                1",                     # recalibration of CC Energy
#"RecalSG                1",                     # recalibration fired Segments
#"TimeShiftCC           f32",                    # time shift of core (ns)
#"Verbose",                                      # more verbose terminal-output
#"TrappingFile          Trapping_$CRYSTAL.cal",  # file with the trapping-correction coefficients
#"NoMultiHist",                                  # exclude local spectra and matrices
#### command lines to be produced only for the specified crystals
{
'00A' : ("TrappingFile Trapping.cal","RecalCC -0.026 1.000972","TimeShiftCC  17.279 ","RecalEnergy2 RecalEnergy2.cal"),
'00B' : ("TrappingFile Trapping.cal","RecalCC  0.213 1.000802","TimeShiftCC  18.567 ","RecalEnergy2 RecalEnergy2.cal"),
'00C' : ("TrappingFile Trapping.cal","RecalCC -0.377 1.000992","TimeShiftCC  20.917 ","RecalEnergy2 RecalEnergy2.cal"),
'01A' : ("TrappingFile Trapping.cal","RecalCC -0.176 1.000590","TimeShiftCC  15.880 ","RecalEnergy2 RecalEnergy2.cal"),
'01B' : ("TrappingFile Trapping.cal","RecalCC -0.112 1.000669","TimeShiftCC   4.593 ","RecalEnergy2 RecalEnergy2.cal"),
'01C' : ("TrappingFile Trapping.cal","RecalCC -0.088 1.001767","TimeShiftCC  20.521 ","RecalEnergy2 RecalEnergy2.cal"),
'02A' : ("TrappingFile Trapping.cal","RecalCC -0.239 0.999051","TimeShiftCC -16.349 ","RecalEnergy2 RecalEnergy2.cal"),
'02B' : ("TrappingFile Trapping.cal","RecalCC -0.203 1.000175","TimeShiftCC  17.867 ","RecalEnergy2 RecalEnergy2.cal"),
'02C' : ("TrappingFile Trapping.cal","RecalCC -0.443 1.000994","TimeShiftCC  22.570 ","RecalEnergy2 RecalEnergy2.cal"),
'03A' : ("TrappingFile Trapping.cal","RecalCC -0.167 1.001117","TimeShiftCC  23.087 ","RecalEnergy2 RecalEnergy2.cal"),
'03B' : ("TrappingFile Trapping.cal","RecalCC -0.235 1.000218","TimeShiftCC  16.271 ","RecalEnergy2 RecalEnergy2.cal"),
'03C' : ("TrappingFile Trapping.cal","RecalCC  0.431 0.999938","TimeShiftCC  18.807 ","RecalEnergy2 RecalEnergy2.cal"),
'04A' : ("TrappingFile Trapping.cal","RecalCC  0.101 0.999328","TimeShiftCC  17.148 ","RecalEnergy2 RecalEnergy2.cal"),
'04B' : ("TrappingFile Trapping.cal","RecalCC -0.049 1.000841","TimeShiftCC  17.408 ","RecalEnergy2 RecalEnergy2.cal"),
'04C' : ("TrappingFile Trapping.cal","RecalCC  0.214 1.000104","TimeShiftCC  17.917 ","RecalEnergy2 RecalEnergy2.cal"),
'05A' : ("TrappingFile Trapping.cal","RecalCC  0.165 1.000608","TimeShiftCC  18.724 ","RecalEnergy2 RecalEnergy2.cal"),
'05B' : ("TrappingFile Trapping.cal","RecalCC  0.330 1.000254","TimeShiftCC -29.446 ","RecalEnergy2 RecalEnergy2.cal"),
'05C' : ("TrappingFile Trapping.cal","RecalCC -0.146 1.000445","TimeShiftCC -29.770 ","RecalEnergy2 RecalEnergy2.cal"),
'06A' : ("TrappingFile Trapping.cal","RecalCC -0.517 1.000140","TimeShiftCC -14.501 ","RecalEnergy2 RecalEnergy2.cal"),
'06B' : ("TrappingFile Trapping.cal","RecalCC  0.516 1.000251","TimeShiftCC -20.870 ","RecalEnergy2 RecalEnergy2.cal"),
'06C' : ("TrappingFile Trapping.cal","RecalCC -1.068 1.001362","TimeShiftCC -18.553 ","RecalEnergy2 RecalEnergy2.cal"),
'07A' : ("TrappingFile Trapping.cal","RecalCC  0.126 1.000447","TimeShiftCC -12.885 ","RecalEnergy2 RecalEnergy2.cal"),
'07B' : ("TrappingFile Trapping.cal","RecalCC  0.323 0.999807","TimeShiftCC -19.794 ","RecalEnergy2 RecalEnergy2.cal"),
'07C' : ("TrappingFile Trapping.cal","RecalCC -1.107 1.000744","TimeShiftCC -32.423 ","RecalEnergy2 RecalEnergy2.cal"),
'09B' : ("TrappingFile Trapping.cal","RecalCC  0.143 1.000471","TimeShiftCC  22.900 ","RecalEnergy2 RecalEnergy2.cal"),
'09C' : ("TrappingFile Trapping.cal","RecalCC -0.333 1.000309","TimeShiftCC -24.571 ","RecalEnergy2 RecalEnergy2.cal"),
'10A' : ("TrappingFile Trapping.cal","RecalCC  0.008 1.000804","TimeShiftCC  20.858 ","RecalEnergy2 RecalEnergy2.cal"),
'10B' : ("TrappingFile Trapping.cal","RecalCC -0.086 0.999421","TimeShiftCC  15.793 ","RecalEnergy2 RecalEnergy2.cal"),
'10C' : ("TrappingFile Trapping.cal","RecalCC -0.615 1.000435","TimeShiftCC  20.921 ","RecalEnergy2 RecalEnergy2.cal"),
'11A' : ("TrappingFile Trapping.cal","RecalCC -0.496 1.005279","TimeShiftCC -24.525 ","RecalEnergy2 RecalEnergy2.cal"),
'11B' : ("TrappingFile Trapping.cal","RecalCC -0.094 1.000300","TimeShiftCC -22.233 ","RecalEnergy2 RecalEnergy2.cal"),
'11C' : ("TrappingFile Trapping.cal","RecalCC -0.076 1.000020","TimeShiftCC -22.921 ","RecalEnergy2 RecalEnergy2.cal"),
'12A' : ("TrappingFile Trapping.cal","RecalCC  0.453 1.000220","TimeShiftCC -17.995 ","RecalEnergy2 RecalEnergy2.cal"),
'12B' : ("TrappingFile Trapping.cal","RecalCC -0.694 1.000011","TimeShiftCC -25.643 ","RecalEnergy2 RecalEnergy2.cal"),
'12C' : ("TrappingFile Trapping.cal","RecalCC  0.105 0.999396","TimeShiftCC -22.526 ","RecalEnergy2 RecalEnergy2.cal"),
'13A' : ("TrappingFile Trapping.cal","RecalCC  0.108 1.000874","TimeShiftCC   8.296 ","RecalEnergy2 RecalEnergy2.cal"),
'13B' : ("TrappingFile Trapping.cal","RecalCC -0.325 1.000496","TimeShiftCC   7.247 ","RecalEnergy2 RecalEnergy2.cal"),
'13C' : ("TrappingFile Trapping.cal","RecalCC -0.214 1.000906","TimeShiftCC  15.329 ","RecalEnergy2 RecalEnergy2.cal"),
'14A' : ("TrappingFile Trapping.cal","RecalCC  0.042 1.000952","TimeShiftCC  15.158 ","RecalEnergy2 RecalEnergy2.cal"),
'14B' : ("TrappingFile Trapping.cal","RecalCC  0.273 1.000097","TimeShiftCC -20.908 ","RecalEnergy2 RecalEnergy2.cal"),
'14C' : ("TrappingFile Trapping.cal","RecalCC -0.646 1.001530","TimeShiftCC -18.146 ","RecalEnergy2 RecalEnergy2.cal"),
}
)

#########################

TrackingFilter=(
"ActualClass           TrackingFilterOFT",       	# name of the used daugther class (TrackingFilterOFT or TrackingFilterMGT)
"SaveDataDir           $SAVEDIR/$MERGER",       	# Out/Global
"EnergyGain            4",                      	# channels/keV of the calibrated energy spectra
#"ExcludeTracking",                             	# skip the tracking part of the actor; remains only the data processing
"OftParams             0.05 0.02 0.8 1",              #  minprobtrack minprobsing sigma_thet (0==default)
#"MgtParams           0                             #  max value of Chi2 to accept a tracked gamma (0==default)
"SourcePosition        0 0 -51",                   # position of source with respect to the center of AGATA Position of source (in code pg->Z1 - fSource[2]) so negative means approached
"DiscardEmpty          0",
#"RecoilDirection       0 0 1",                     # fixed recoil direction for Doppler correction (if not using info from Ancillary) 
#"RecoilBeta            0.05",                  	# and beta of recoil
#"CoreEnergyGate        20 20000",               	# possibility to restrict the energy range in the individual detectors (better in PreprocessingFilter)
#"NumDetsGate         i32 i32",                     # event selection based on number of fired detectors
#"NumHitsGate         i32 i32",                     # event selection based on total number of hits
#"WriteRootTree",                                	# enable writing the root tree
#"WriteRootTree         InputHits",              	# enable writing the root tree with the input hits
#"WriteMgtData",                                    # enable writing Mgt_Hits.txt (same as: WriteInputHits WriteMgtHits WriteOftHits)
#"WriteTracked",                                    # write file of input hits for analysis with OFT
#"RotoTranslations CrystalPositionLookUpTable",     # this is the default
#"Matrixgg1             4096 1",                    # size and gain of g-g matrix for CC before tracking (default size is 0 ==> no matrix)
#"Matrixgg2             4096 1",                    # size and gain of g-g matrix for tracked and Doppler corrected gammas (   ""   )
#"MatrixZYX           f32 f32 i32 f32",             # hits and intercepts: zOffset and zScale for hits; range and scale of z-planes
#"OutputModel           kSafe",                    	# kStrict (default)  kSafe  kGrowing, behaviour for ADF
#"Verbose",                                         # more verbose terminal-output
"NumGeDets  41",                                     # Overrides the default number of Ge Crystals [20], just for printing of TkT spectra
"SpecMap 0 0",
"SpecMap 1 1",
"SpecMap 2 2",
"SpecMap 3 3",
"SpecMap 4 4",
"SpecMap 5 5",
"SpecMap 6 6",
"SpecMap 7 7",
"SpecMap 8 8",
"SpecMap 9 9",
"SpecMap 10 10",
"SpecMap 11 11",
"SpecMap 12 12",
"SpecMap 13 13",
"SpecMap 14 14",
"SpecMap 15 15",
"SpecMap 16 16",
"SpecMap 17 17",
"SpecMap 18 18",
"SpecMap 19 19",
"SpecMap 20 20",
"SpecMap 21 21",
"SpecMap 22 22",
"SpecMap 23 23",
"SpecMap 28 24",
"SpecMap 29 25",
"SpecMap 30 26",
"SpecMap 31 27",
"SpecMap 32 28",
"SpecMap 33 29",
"SpecMap 34 30",
"SpecMap 35 31",
"SpecMap 36 32",
"SpecMap 37 33",
"SpecMap 38 34",
"SpecMap 39 35",
"SpecMap 40 36",
"SpecMap 41 37",
"SpecMap 42 38",
"SpecMap 43 39",
"SpecMap 44 40",

#When active with ancillary ######################33
#"KeepEmpty",                                   	# send to the adf output also events without gammas
#"DiscardEmpty 0",                                	# remove from the adf output events without gammas
#"AncillaryRawFrame     0",                     	# 0 (GSI)	0 (GANIL) 1 (LNL)    default is 1
#"Ancillary",                                   	# to perform tracking only if ancillary data is present
#"Recoiling",                                       # Doppler shift correction to be done using event-by-event recoil direction from Ancillary
#"TimeWindowGeAnc       650 670",                 # values should be taken from Oft__**__TA.spec
#"TimeWindowGeAncillary 1110 1130",               # variant of the previous
#"WriteMgtData          Ancillary Timing Extended", # enable writing Mgt_Hits.txt with ancillary,... data
)   

#########################
EventBuilder=(
"ActualClass           EventBuilder",             # name of the used daugther class
"SaveDataDir           $SAVEDIR/$BUILDER",        # Out/Builder
"Window         50",                              # EventNumber also possible but not working well
#"TstampWindow   ui64 ui64",                      # coincidence window 'width' or 'from to' (timestamp units)
"keyIn                 data:psa",                 # key of 1st queue.  
"keyIn                 data:psa",                 # key of 2nd queue. 'None' to not have the surrounding frame
"keyOut                event:data:psa",           # key of the output frame default is event:data. 'None' to not have the surrounding frame
"MinFold               1",                        # 2 if you want to force the coincidence between 2 AGATA                       
#"TimestampCorrect      0  -128",                 # indexed by the input queue number !!
#"TstampLimits   ui32 ui32",                      # discard events outside this data-timestamp interval (seconds)
#"TstampRegions  ui64 ui64 str",                  # tStampMin, tStampStep, TxtFile with 0/1 for each timestamp step
#"RateProfile    ui64 ui64 i32",                  # tStampMin, tStampStep, Length of rate-profile spectrum
#"Details        15 ",                            # bit1=tstamp_snapshot  bit2=tstamp_diff for all input queues, bit3=TAC for all pairs
"Verbose",                                        # more verbose terminal-output
)
#########################
BasicATSB_DIAMANT=(
"ActualClass    BasicATSB",             # name of the used daugther class
"timewindow     40",                    #Time window for the event building of NEDA/DIAMANT
"ikey:          data:ranc1  1  152 ",   #input key (data:ranc0 for NEDA / data:ranc1 for  DIAMANT), Min multiplicity threshold, Max multiplicity threshold 
"okey:          event:data:ranc1",      #output key (event:data:ranc0 for NEDA /event:data:ranc1 for  DIAMANT) 
)


#########################
BasicATSB_NEDA=(
"ActualClass    BasicATSB",             # name of the used daugther class
"timewindow     40",                    #Time window for the event building of NEDA/DIAMANT
"ikey:          data:ranc0  1  152 ",   #input key (data:ranc0 for NEDA / data:ranc1 for  DIAMANT), Min multiplicity threshold, Max multiplicity threshold 
"okey:          event:data:ranc0",      #output key (event:data:ranc0 for NEDA /event:data:ranc1 for  DIAMANT) 
)

#########################
EventMerger_MERGER=(
"ActualClass           EventMerger",             # name of the used daugther class
"SaveDataDir           $SAVEDIR/$MERGER ",        # Out/Merger
"Window                250",            # EventNumber also possible but not working well
#"TstampWindow   ui64 ui64",                      # coincidence window 'width' or 'from to' (timestamp units)
"keyIn                 event:data:psa", 		  # key of 1st queue.  
"keyIn                 data:ranc0",			    # key of 2nd queue. 
#"keyIn                 data:ranc1",			    # key of 3rd queue.
"keyOut                event:data",               # key of the output frame default is event:data. 'None' to not have the surrounding frame
"MandatoryKey          data:ranc0",           #For Merger, key that needs to be triggered to validate the event

#"keyIn                 data:psa",                 # key of 1st queue.  
#"keyIn                 data:psa",                 # key of 2nd queue. 'None' to not have the surrounding frame
#"keyOut                event:data:psa",           # key of the output frame default is event:data. 'None' to not have the surrounding frame
"MinFold               1",                        # 2 if you want to force the coincidence between AGATA and the Ancillary                       
#"TimestampCorrect      0  -128",                 # indexed by the input queue number !!
#"TstampLimits   ui32 ui32",                      # discard events outside this data-timestamp interval (seconds)
#"TstampRegions  ui64 ui64 str",                  # tStampMin, tStampStep, TxtFile with 0/1 for each timestamp step
#"RateProfile    ui64 ui64 i32",                  # tStampMin, tStampStep, Length of rate-profile spectrum
#"Details        i32 ",                           # bit1=tstamp_snapshot  bit2=tstamp_diff for all input queues, bit3=TAC for all pairs
"Verbose",                                        # more verbose terminal-output
)
#########################

# Configuration of the consumers:

BasicAFC_VAMOS=(                                
"$SAVEDIR/$VAMOS         vamos_ 0",           
)

BasicAFC_NEDA=(                                
"$SAVEDIR/$BUILDNEDA         Builder_neda_ 0",           
)

BasicAFC_DIAMANT=(                                
"$SAVEDIR/$BUILDDIAMANT         Builder_diamant_ 0",          
)

BasicAFC_BUILDER=(                              # _BUILDER will be removed when building the name of the file
"$SAVEDIR/$BUILDER      Builder_ 0",            # name of the final adf file "Builder_0000.adf"
)

BasicAFC_MERGER=(                               # _MERGER will be removed when building the name of the file
"$SAVEDIR/$MERGER       Tracked_ 0",             # name of the final adf file "Merger_0000.adf"
)

BasicAFC_GLOBAL=(                               # _GLOBAL will be removed when building the name of the file
"$SAVEDIR/$GLOBAL       Tracked_ 0",            # name of the final adf file "Tracked_0000.adf"
)
 
BasicAFC=(                                       
"$SAVEDIR/$CRYSTAL       SRM_AGATA_psa_ 0",               # name of the final adf file "Tracked_0000.adf"
)


# Configuration of the producerss:
BasicAFP_CRYSTAL=(                         
"$READDIR/$CRYSTAL       SRM_AGATA_psa_ 0",         
)

BasicAFP_VAMOS=(                                
"$READDIR/$VAMOS         SRM_AGATA_vamos_ 0",             # it reads adf file "vamos_0000.adf"
)
BasicAFP_NEDA=(                                
"$READDIR/$NEDA         neda_ 0",             # it reads adf file "Neda_0000.adf"
)

BasicAFP_DIAMANT=(                                
"$READDIR/$DIAMANT       diamant_ 0",             # it reads adf file "vamos_0000.adf"
)

BasicAFP_BUILDNEDA=(                                
"$READDIR/$BUILDNEDA         Builder_neda_ 0",             # it reads adf file "Neda_0000.adf"
)

BasicAFP_BUILDDIAMANT=(                                
"$READDIR/$BUILDDIAMANT         Builder_diamant_ 0",             # it reads adf file "vamos_0000.adf"
)

BasicAFP_BUILDER=(                              # _BUILDER will be removed when building the name of the file
"$READDIR/$BUILDER      Builder_ 0",            # name of the final adf file "Builder_0000.adf"
)

BasicMFMP=(                                
"l vamos.mfm",
)

TreeBuilder=(  #From 2019                                     
"ActualClass    TreeBuilder",      		 	             # name of the used daugther class
"SaveDataDir    $SAVEDIR/$ANALYSIS   Tree_  TreeMaster ",            # name of the final root file "AgNedDiamTree_0000.root"
"AddDetector    AGATA_BUILDER   event:data:psa         0",           # Add a detector in the Tree (DetName, ADF key, Mode [-1: Must NOT be present, 0: Can be present, 1: Must be present])
#"AddDetector    AGATA_TRACKING  data:tracked           0",           # Add a detector in the Tree (DetName, ADF key, Mode [-1: Must NOT be present, 0: Can be present, 1: Must be present])
"AddDetector    VAMOS           data:ranc0             0",           # Add a detector in the Tree (DetName, ADF key, Mode [-1: Must NOT be present, 0: Can be present, 1: Must be present])
)

ProdHist=( 
"Crystal                $CRYSTAL",		# Crystal name                                    
"RefreshTime		5",			# Refresh time of the Shared Memory Zone (in seconds)
"PlotAmpli              4096 0 4096",		# Binning of the amplitude spectra
"PlotSignals            4096 0 4096",		# Binning of the baseline spectra
"PlotTimeStamps         1",			# Plot Timestamp spectra, optionnal: define the ref T0 TimeStamp (1 TSRef)
)

PreproHist=( 
"Crystal                $CRYSTAL",		# Crystal name
"RefreshTime		5",			# Refresh time of the Shared Memory Zone (in seconds)                               
"PlotAmpli              4096 0 4096",		# Binning of the amplitude spectra
"PlotAmplivsSegId       1024 0 16384 38 0 38",	# Binning of the E_vs_id matrice	
"PlotBaseline           1000 -50 50",		# Binning of the baseline spectra
"PlotT0                 1000 0 1000",		# Binning of the T0 spectra
"PlotDeltaT             4000 0 400000",		# Binning of the DeltaT spectrum
"PlotTimeStamps         1",			# Plot Timestamp spectra, optionnal: define the ref T0 TimeStamp (1 TSRef)
)

PSAHist=( 
"Crystal                $CRYSTAL",		# Crystal name
"RefreshTime            5",			# Refresh time of the Shared Memory Zone (in seconds)                               
"PlotAmpli              4096 0 4096",		# Binning of the amplitude spectra
"PlotCoreT              1000 0 100",	        # Binning of the Core timing spectra	
"PlotHitPaterns         1",			# Plot hit paterns (XvsY per slice, ZvsY, ZvsR, hit multiplicity
"PlotTimeStamps         1",			# Plot Timestamp spectra, optionnal: define the ref T0 TimeStamp (1 TSRef)
)

TB_VAMOS=(                                       
#"BRho          1.05",                             	  # BRho
#"BRho          0.95",                             	  # BRho =>From Run 58
"BRho          0.90",                             	  # BRho =>From Run 62
"ActionFile    ACTIONS_e786s.CHC_PAR",                    # Action file name"
"VamosConfPath $CONFDIR/../ConfVAMOS",                       # Vamos configuration files path
)

#TreeBuilder=(      #for 2018 data                                 
#"ActualClass    TB_AgNedDiam",      		 	             # name of the used daugther class
#"SaveDataDir 	$SAVEDIR/$ANALYSIS   AgNedDiamTree_  TreeMaster ",   # name of the final root file "AgNedDiamTree_0000.root"
#)



##################
#######

###############################################################################################
###################  3  Database of AGATA germanium detectors  ################################
###############################################################################################

# These values should be checked carefully against the detector configuration used to take the data

GeDataBase2012_perf_com={
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B012.dat'], '00C': ['02', '$PSABASE/LibTrap_C010.dat'], 
'01A': ['03', '$PSABASE/LibTrap_A001.dat'], '01B': ['04', '$PSABASE/LibTrap_B012.dat'], '01C': ['05', '$PSABASE/LibTrap_C010.dat'], 
'04A': ['12', '$PSABASE/LibTrap_A001.dat'], '04B': ['13', '$PSABASE/LibTrap_B008.dat'], '04C': ['14', '$PSABASE/LibTrap_C006.dat'], 
'06A': ['18', '$PSABASE/LibTrap_A001.dat'], '06B': ['19', '$PSABASE/LibTrap_B012.dat'], '06C': ['20', '$PSABASE/LibTrap_C001.dat'], 
'12A': ['36', '$PSABASE/LibTrap_A008.dat'], '12B': ['37', '$PSABASE/LibTrap_B001.dat'], '12C': ['38', '$PSABASE/LibTrap_C003.dat'], 
'13A': ['39', '$PSABASE/LibTrap_A002.dat'], '13B': ['40', '$PSABASE/LibTrap_B010.dat'], '13C': ['41', '$PSABASE/LibTrap_C001.dat'], 
'14A': ['42', '$PSABASE/LibTrap_A002.dat'], '14B': ['43', '$PSABASE/LibTrap_B010.dat'], '14C': ['44', '$PSABASE/LibTrap_C001.dat'], 
}
#This are the correct ones for the configuration of sep-oct 2012 in GSI, done the 21092012
GeDataBase2012_Oct={
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B011.dat'], '00C': ['02', '$PSABASE/LibTrap_C008.dat'], 
'01A': ['03', '$PSABASE/LibTrap_A001.dat'], '01B': ['04', '$PSABASE/LibTrap_B012.dat'], '01C': ['05', '$PSABASE/LibTrap_C010.dat'], 
'04A': ['12', '$PSABASE/LibTrap_A001.dat'], '04B': ['13', '$PSABASE/LibTrap_B008.dat'], '04C': ['14', '$PSABASE/LibTrap_C006.dat'], 
'06A': ['18', '$PSABASE/LibTrap_A001.dat'], '06B': ['19', '$PSABASE/LibTrap_B004.dat'], '06C': ['20', '$PSABASE/LibTrap_C001.dat'], 
'07A': ['21', '$PSABASE/LibTrap_A003.dat'], '07B': ['22', '$PSABASE/LibTrap_B003.dat'], '07C': ['23', '$PSABASE/LibTrap_C005.dat'], 
'12A': ['36', '$PSABASE/LibTrap_A008.dat'], '12B': ['37', '$PSABASE/LibTrap_B001.dat'], '12C': ['38', '$PSABASE/LibTrap_C003.dat'], 
'13A': ['39', '$PSABASE/LibTrap_A002.dat'], '13B': ['40', '$PSABASE/LibTrap_B010.dat'], '13C': ['41', '$PSABASE/LibTrap_C001.dat'], 
'14A': ['42', '$PSABASE/LibTrap_A004.dat'], '14B': ['43', '$PSABASE/LibTrap_B002.dat'], '14C': ['44', '$PSABASE/LibTrap_C004.dat'], 
'99A': ['33', '$PSABASE/LibTrap_A004.dat'], '99B': ['33', '$PSABASE/LibTrap_B002.dat'], '99C': ['33', '$PSABASE/LibTrap_C004.dat'], 
}
#This are the configuration planned for the 2014 GSI runs
GeDataBase2014={
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B011.dat'], '00C': ['02', '$PSABASE/LibTrap_C008.dat'], 
'01A': ['03', '$PSABASE/LibTrap_A001.dat'], '01B': ['04', '$PSABASE/LibTrap_B012.dat'], '01C': ['05', '$PSABASE/LibTrap_C010.dat'], 
'04A': ['12', '$PSABASE/LibTrap_A001.dat'], '04B': ['13', '$PSABASE/LibTrap_B008.dat'], '04C': ['14', '$PSABASE/LibTrap_C006.dat'], 
'05A': ['15', '$PSABASE/LibTrap_A004.dat'], '05B': ['16', '$PSABASE/LibTrap_B002.dat'], '05C': ['17', '$PSABASE/LibTrap_C004.dat'], 
'07A': ['21', '$PSABASE/LibTrap_A003.dat'], '07B': ['22', '$PSABASE/LibTrap_B003.dat'], '07C': ['23', '$PSABASE/LibTrap_C005.dat'], 
'12A': ['36', '$PSABASE/LibTrap_A001.dat'], '12B': ['37', '$PSABASE/LibTrap_B004.dat'], '12C': ['38', '$PSABASE/LibTrap_C099.dat'], 
'13A': ['39', '$PSABASE/LibTrap_A002.dat'], '13B': ['40', '$PSABASE/LibTrap_B010.dat'], '13C': ['41', '$PSABASE/LibTrap_C001.dat'], 
'14A': ['42', '$PSABASE/LibTrap_A007.dat'], '14B': ['43', '$PSABASE/LibTrap_B007.dat'], '14C': ['44', '$PSABASE/LibTrap_C007.dat'], 
'99A': ['33', '$PSABASE/LibTrap_A004.dat'], '99B': ['33', '$PSABASE/LibTrap_B002.dat'], '99C': ['33', '$PSABASE/LibTrap_C004.dat'], 
}
#This are the configuration GANIL: DO NOT MODIFY !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
GeDataBaseGANIL={
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B004.dat'], '00C': ['02', '$PSABASE/LibTrap_C010.dat'], 
'02A': ['06', '$PSABASE/LibTrap_A009.dat'], '02B': ['07', '$PSABASE/LibTrap_B005.dat'], '02C': ['08', '$PSABASE/LibTrap_C008.dat'], 
'03A': ['09', '$PSABASE/LibTrap_A005.dat'], '03B': ['10', '$PSABASE/LibTrap_B002.dat'], '03C': ['11', '$PSABASE/LibTrap_C009.dat'],  
'04A': ['12', '$PSABASE/LibTrap_A008.dat'], '04B': ['13', '$PSABASE/LibTrap_B001.dat'], '04C': ['14', '$PSABASE/LibTrap_C003.dat'], 
'10A': ['30', '$PSABASE/LibTrap_A003.dat'], '10B': ['31', '$PSABASE/LibTrap_B003.dat'], '10C': ['32', '$PSABASE/LibTrap_C005.dat'], 
'11A': ['33', '$PSABASE/LibTrap_A006.dat'], '11B': ['34', '$PSABASE/LibTrap_B013.dat'], '11C': ['35', '$PSABASE/LibTrap_C006.dat'], 
'12A': ['36', '$PSABASE/LibTrap_A002.dat'], '12B': ['37', '$PSABASE/LibTrap_B010.dat'], '12C': ['38', '$PSABASE/LibTrap_C001.dat'], 
'13A': ['39', '$PSABASE/LibTrap_A007.dat'], '13B': ['40', '$PSABASE/LibTrap_B007.dat'], '13C': ['41', '$PSABASE/LibTrap_C007.dat'],  
'20A': ['02', '$PSABASE/LibTrap_C010.dat'], '20B': ['08', '$PSABASE/LibTrap_C008.dat'],   
}
GeDataBaseGANIL2016={ #CM : C012 for 04C has to be changed with C013....
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B004.dat'], '00C': ['02', '$PSABASE/LibTrap_C010.dat'],
'01A': ['03', '$PSABASE/LibTrap_A010.dat'], '01B': ['04', '$PSABASE/LibTrap_B012.dat'], '01C': ['05', '$PSABASE/LibTrap_C014.dat'], 
'02A': ['06', '$PSABASE/LibTrap_A009.dat'], '02B': ['07', '$PSABASE/LibTrap_B005.dat'], '02C': ['08', '$PSABASE/LibTrap_C008.dat'], 
'03A': ['09', '$PSABASE/LibTrap_A005.dat'], '03B': ['10', '$PSABASE/LibTrap_B002.dat'], '03C': ['11', '$PSABASE/LibTrap_C009.dat'],  
'04A': ['12', '$PSABASE/LibTrap_A004.dat'], '04B': ['13', '$PSABASE/LibTrap_B008.dat'], '04C': ['14', '$PSABASE/LibTrap_C012.dat'], 
'05A': ['15', '$PSABASE/LibTrap_A011.dat'], '05B': ['16', '$PSABASE/LibTrap_B006.dat'], '05C': ['17', '$PSABASE/LibTrap_C012.dat'], 
'09B': ['28', '$PSABASE/LibTrap_B011.dat'], '09C': ['29', '$PSABASE/LibTrap_C011.dat'], 
'10A': ['30', '$PSABASE/LibTrap_A003.dat'], '10B': ['31', '$PSABASE/LibTrap_B003.dat'], '10C': ['32', '$PSABASE/LibTrap_C005.dat'], 
'11A': ['33', '$PSABASE/LibTrap_A006.dat'], '11B': ['34', '$PSABASE/LibTrap_B013.dat'], '11C': ['35', '$PSABASE/LibTrap_C006.dat'], 
'12A': ['36', '$PSABASE/LibTrap_A002.dat'], '12B': ['37', '$PSABASE/LibTrap_B010.dat'], '12C': ['38', '$PSABASE/LibTrap_C001.dat'], 
'13A': ['39', '$PSABASE/LibTrap_A007.dat'], '13B': ['40', '$PSABASE/LibTrap_B007.dat'], '13C': ['41', '$PSABASE/LibTrap_C007.dat'],  
'14A': ['42', '$PSABASE/LibTrap_A012.dat'], '14B': ['43', '$PSABASE/LibTrap_B009.dat'], '14C': ['44', '$PSABASE/LibTrap_C004.dat'],  
}
GeDataBaseGANIL2017={ 
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B004.dat'], '00C': ['02', '$PSABASE/LibTrap_C010.dat'],
'02A': ['06', '$PSABASE/LibTrap_A009.dat'], '02B': ['07', '$PSABASE/LibTrap_B005.dat'], '02C': ['08', '$PSABASE/LibTrap_C008.dat'], 
'03A': ['09', '$PSABASE/LibTrap_A005.dat'], '03B': ['10', '$PSABASE/LibTrap_B002.dat'], '03C': ['11', '$PSABASE/LibTrap_C009.dat'],  
'04A': ['12', '$PSABASE/LibTrap_A004.dat'], '04B': ['13', '$PSABASE/LibTrap_B008.dat'], '04C': ['14', '$PSABASE/LibTrap_C002.dat'],
'05A': ['15', '$PSABASE/LibTrap_A011.dat'], '05B': ['16', '$PSABASE/LibTrap_B006.dat'], '05C': ['17', '$PSABASE/LibTrap_C012.dat'],
'06A': ['18', '$PSABASE/LibTrap_A012.dat'], '06B': ['19', '$PSABASE/LibTrap_B009.dat'], '06C': ['20', '$PSABASE/LibTrap_C004.dat'], 
'09B': ['28', '$PSABASE/LibTrap_B011.dat'], '09C': ['29', '$PSABASE/LibTrap_C011.dat'], 
'10A': ['30', '$PSABASE/LibTrap_A003.dat'], '10B': ['31', '$PSABASE/LibTrap_B003.dat'], '10C': ['32', '$PSABASE/LibTrap_C005.dat'], 
'11A': ['33', '$PSABASE/LibTrap_A006.dat'], '11B': ['34', '$PSABASE/LibTrap_B013.dat'], '11C': ['35', '$PSABASE/LibTrap_C006.dat'], 
'12A': ['36', '$PSABASE/LibTrap_A010.dat'], '12B': ['37', '$PSABASE/LibTrap_B012.dat'], '12C': ['38', '$PSABASE/LibTrap_C014.dat'], 
'13A': ['39', '$PSABASE/LibTrap_A007.dat'], '13B': ['40', '$PSABASE/LibTrap_B007.dat'], '13C': ['41', '$PSABASE/LibTrap_C007.dat'],  
'14A': ['42', '$PSABASE/LibTrap_A014.dat'], '14B': ['43', '$PSABASE/LibTrap_B016.dat'], '14C': ['44', '$PSABASE/LibTrap_C016.dat'],  
}
GeDataBaseGANIL2018={ 
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B004.dat'], '00C': ['02', '$PSABASE/LibTrap_C010.dat'],
'01A': ['03', '$PSABASE/LibTrap_A008.dat'], '01B': ['04', '$PSABASE/LibTrap_B002.dat'], '01C': ['05', '$PSABASE/LibTrap_C009.dat'],  
'02A': ['06', '$PSABASE/LibTrap_A009.dat'], '02B': ['07', '$PSABASE/LibTrap_B005.dat'], '02C': ['08', '$PSABASE/LibTrap_C008.dat'], 
'03A': ['09', '$PSABASE/LibTrap_A013.dat'], '03B': ['10', '$PSABASE/LibTrap_B014.dat'], '03C': ['11', '$PSABASE/LibTrap_C015.dat'], 
'04A': ['12', '$PSABASE/LibTrap_A004.dat'], '04B': ['13', '$PSABASE/LibTrap_B008.dat'], '04C': ['14', '$PSABASE/LibTrap_C002.dat'],
'05A': ['15', '$PSABASE/LibTrap_A011.dat'], '05B': ['16', '$PSABASE/LibTrap_B006.dat'], '05C': ['17', '$PSABASE/LibTrap_C012.dat'],
'06A': ['18', '$PSABASE/LibTrap_A012.dat'], '06B': ['19', '$PSABASE/LibTrap_B009.dat'], '06C': ['20', '$PSABASE/LibTrap_C004.dat'], 
'09B': ['28', '$PSABASE/LibTrap_B011.dat'], '09C': ['29', '$PSABASE/LibTrap_C011.dat'], 
'10A': ['30', '$PSABASE/LibTrap_A003.dat'], '10B': ['31', '$PSABASE/LibTrap_B003.dat'], '10C': ['32', '$PSABASE/LibTrap_C005.dat'], 
'11A': ['33', '$PSABASE/LibTrap_A006.dat'], '11B': ['34', '$PSABASE/LibTrap_B013.dat'], '11C': ['35', '$PSABASE/LibTrap_C006.dat'], 
'13A': ['39', '$PSABASE/LibTrap_A007.dat'], '13B': ['40', '$PSABASE/LibTrap_B007.dat'], '13C': ['41', '$PSABASE/LibTrap_C007.dat'],  
'14A': ['42', '$PSABASE/LibTrap_A014.dat'], '14B': ['43', '$PSABASE/LibTrap_B016.dat'], '14C': ['44', '$PSABASE/LibTrap_C016.dat'],  
}
GeDataBaseGANIL2019={ 
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B004.dat'], '00C': ['02', '$PSABASE/LibTrap_C010.dat'],
'01A': ['03', '$PSABASE/LibTrap_A008.dat'], '01B': ['04', '$PSABASE/LibTrap_B002.dat'], '01C': ['05', '$PSABASE/LibTrap_C009.dat'],  
'02A': ['06', '$PSABASE/LibTrap_A009.dat'], '02B': ['07', '$PSABASE/LibTrap_B005.dat'], '02C': ['08', '$PSABASE/LibTrap_C008.dat'], 
'03A': ['09', '$PSABASE/LibTrap_A013.dat'], '03B': ['10', '$PSABASE/LibTrap_B014.dat'], '03C': ['11', '$PSABASE/LibTrap_C015.dat'], 
'04A': ['12', '$PSABASE/LibTrap_A004.dat'], '04B': ['13', '$PSABASE/LibTrap_B008.dat'], '04C': ['14', '$PSABASE/LibTrap_C002.dat'],
'05A': ['15', '$PSABASE/LibTrap_A011.dat'], '05B': ['16', '$PSABASE/LibTrap_B006.dat'], '05C': ['17', '$PSABASE/LibTrap_C012.dat'],
'06A': ['18', '$PSABASE/LibTrap_A012.dat'], '06B': ['19', '$PSABASE/LibTrap_B009.dat'], '06C': ['20', '$PSABASE/LibTrap_C004.dat'],
'07A': ['21', '$PSABASE/LibTrap_A002.dat'], '07B': ['22', '$PSABASE/LibTrap_B010.dat'], '07C': ['23', '$PSABASE/LibTrap_C001.dat'],
'09B': ['28', '$PSABASE/LibTrap_B011.dat'], '09C': ['29', '$PSABASE/LibTrap_C011.dat'], 
'10A': ['30', '$PSABASE/LibTrap_A003.dat'], '10B': ['31', '$PSABASE/LibTrap_B003.dat'], '10C': ['32', '$PSABASE/LibTrap_C005.dat'], 
'11A': ['33', '$PSABASE/LibTrap_A006.dat'], '11B': ['34', '$PSABASE/LibTrap_B013.dat'], '11C': ['35', '$PSABASE/LibTrap_C006.dat'],
'12A': ['36', '$PSABASE/LibTrap_A010.dat'], '12B': ['37', '$PSABASE/LibTrap_B012.dat'], '12C': ['38', '$PSABASE/LibTrap_C014.dat'],
'13A': ['39', '$PSABASE/LibTrap_A007.dat'], '13B': ['40', '$PSABASE/LibTrap_B007.dat'], '13C': ['41', '$PSABASE/LibTrap_C007.dat'],  
'14A': ['42', '$PSABASE/LibTrap_A014.dat'], '14B': ['43', '$PSABASE/LibTrap_B016.dat'], '14C': ['44', '$PSABASE/LibTrap_C016.dat'],  
}
GeDataBaseGANIL2019_2={ 
'00A': ['00', '$PSABASE/LibTrap_A001.dat'], '00B': ['01', '$PSABASE/LibTrap_B004.dat'], '00C': ['02', '$PSABASE/LibTrap_C010.dat'],
'01A': ['03', '$PSABASE/LibTrap_A008.dat'], '01B': ['04', '$PSABASE/LibTrap_B002.dat'], '01C': ['05', '$PSABASE/LibTrap_C009.dat'],  
'02A': ['06', '$PSABASE/LibTrap_A009.dat'], '02B': ['07', '$PSABASE/LibTrap_B005.dat'], '02C': ['08', '$PSABASE/LibTrap_C008.dat'], 
'03A': ['09', '$PSABASE/LibTrap_A013.dat'], '03B': ['10', '$PSABASE/LibTrap_B014.dat'], '03C': ['11', '$PSABASE/LibTrap_C015.dat'], 
'04A': ['12', '$PSABASE/LibTrap_A004.dat'], '04B': ['13', '$PSABASE/LibTrap_B008.dat'], '04C': ['14', '$PSABASE/LibTrap_C002.dat'],
'05A': ['15', '$PSABASE/LibTrap_A011.dat'], '05B': ['16', '$PSABASE/LibTrap_B006.dat'], '05C': ['17', '$PSABASE/LibTrap_C012.dat'],
'06A': ['18', '$PSABASE/LibTrap_A015.dat'], '06B': ['19', '$PSABASE/LibTrap_B009.dat'], '06C': ['20', '$PSABASE/LibTrap_C013.dat'],
'07A': ['21', '$PSABASE/LibTrap_A002.dat'], '07B': ['22', '$PSABASE/LibTrap_B010.dat'], '07C': ['23', '$PSABASE/LibTrap_C001.dat'],
'09B': ['28', '$PSABASE/LibTrap_B011.dat'], '09C': ['29', '$PSABASE/LibTrap_C011.dat'], 
'10A': ['30', '$PSABASE/LibTrap_A003.dat'], '10B': ['31', '$PSABASE/LibTrap_B003.dat'], '10C': ['32', '$PSABASE/LibTrap_C005.dat'], 
'11A': ['33', '$PSABASE/LibTrap_A006.dat'], '11B': ['34', '$PSABASE/LibTrap_B013.dat'], '11C': ['35', '$PSABASE/LibTrap_C006.dat'],
'12A': ['36', '$PSABASE/LibTrap_A010.dat'], '12B': ['37', '$PSABASE/LibTrap_B012.dat'], '12C': ['38', '$PSABASE/LibTrap_C014.dat'],
'13A': ['39', '$PSABASE/LibTrap_A007.dat'], '13B': ['40', '$PSABASE/LibTrap_B007.dat'], '13C': ['41', '$PSABASE/LibTrap_C007.dat'],  
'14A': ['42', '$PSABASE/LibTrap_A014.dat'], '14B': ['43', '$PSABASE/LibTrap_B016.dat'], '14C': ['44', '$PSABASE/LibTrap_C016.dat'],  
}
GeDataBase = GeDataBaseGANIL2019_2

###############################################################################################
######  Code to generate directories and files. You should not need to modify this part.  #####
###############################################################################################

import os.path
import shutil
import sys
import optparse

verbose = False
verbstr = ""

def getGeData(cr):
    """
    get data of crystal cr from GeDataBase
    """
    if cr in GeDataBase:
        if GeDataBase[cr] != ['','']:
          return GeDataBase[cr]
        else:
          print 'GeDataBase for',cr,'is empty'
          sys.exit(-1)      
    else:
        print cr, ' is not in GeDataBase'
        sys.exit(-1)

def replaceMacros(ss, cr):
    """
    replace macros (as defined in MACROS) in string ss. If cr is a Ge crystal (e.g. 1R), its data 
    ($CRYSTAL_ID and $SIGNAL_BASIS are extracted from GeDataBase and replaced before checking MACRO
    """
    if (len(cr) == 2 or len(cr)==3):    # 2 characters for the ge crystals
        dd = getGeData(cr)
        ll = ss.replace("$CRYSTAL_ID",   dd[0])
        ll = ll.replace("$SIGNAL_BASIS", dd[1])
        ll = ll.replace("$CRYSTAL", cr)
    else: 
        ll = ss
    for mm in MACROS:
        ll = ll.replace(mm, MACROS[mm])
    return ll

def printItem(vv, cc, ff):
    """
    item vv relative to the chain cc is printed to file ff, after macro replacement.
    If vv is a tuple or a list, its components are printed in separate lines 
    """
    if isinstance(vv, list) or isinstance(vv, tuple):
        # multi line: recursively call printItem for the elements 
        for vi in vv:
            printItem(vi, cc, ff)
    else:
        # single line: replace macros and print it
        ll = replaceMacros(vv, cc) 
        if CONFTYPE != 'ONLINE' or ll.find('ReadDataDir')!=0:
            ff.write(ll+os.linesep)
            #print ll+os.linesep

def printActor(vv, cc, ff):
    """
    print the command lines in vv to file ff of analysis chain cc
    """
    global verbstr
    #import pdb; pdb.set_trace()
    if len(ff) < 1:
        return
    if os.path.exists(ff):
        if verbose:
            print " Replaced ", ff
        else:
            verbstr += "."
    else:
        print " Created  ", ff
    with open(ff, "w") as fi:
        for vi in vv:
            if isinstance(vi, dict):
                if cc in vi:
                    # dictionary refers to the present detector
                    printItem(vi[cc], cc, fi)
            else:
                # common item
                printItem(vi, cc, fi)

def checkMakeDirs(dd):
    """
    created sub-directory dd in $CONFDIR, $READDIR and $SAVEDIR
    """
    for cc in ['$CONFDIR', '$READDIR', '$SAVEDIR']:
        if cc in MACROS:   
            ff = os.path.join(MACROS[cc], dd)
            if os.path.exists(ff) == False:
                print 'Creating  ', ff
                os.makedirs(ff)

def makeFileName(pre, cc, aa, topo):
    """
    generate the actual name of the configuration file pre/cc/aa
    if the generated filename contains "_topo" this part is removed 
    """
    #import pdb; pdb.set_trace()
    if PROGTYPE == "NARVAL" :
        if aa == "EventBuilder" or aa == "EventMerger" :
            print (" "+aa+".conf").ljust(18), "not generated when using NARVAL"
            return ""
    ff = os.path.join(pre, cc, aa+'.conf')
    ff = ff.replace('_'+topo, '')
    return ff

def checkExtraFiles(new, old, dd, files):
    """
    check existence of the files defined in ExtraFiles. Try to copy it from
    oldDir if file not present and the script is launched with "-o oldDir" 
    """
    global verbstr
    newDir = os.path.join(new, dd)
    oldDir = os.path.join(old, dd)
    for f in files.split():
        fff = os.path.join(newDir, f)
        ff  = replaceMacros(fff, dd) 
        if os.path.exists(ff):
            if verbose:
                print " Existing ", ff
            else:
                verbstr += "."
        else:
            if old != "":
                 gg = os.path.join(oldDir, f)
                 if os.path.exists(gg):
                     if os.path.isdir(gg):
                         shutil.copytree(gg, ff)
                     else:
                         shutil.copy(gg, ff)
                     print " Copied   ", gg
            if not os.path.exists(ff):
                print " Missing  ", ff 

def checkArgsAndMacros():
    """
    decode command line arguments and perform some consistency checks on PROGTYPE and CONFTYPE
    """
    parser = optparse.OptionParser()
    parser.add_option("-o", "--old", dest="confold", help="old Conf where to look for missing auxiliary files", metavar="DIR")
    parser.add_option("-d", "--dir", dest="workdir", help="the directory where to generate the analysis structure", metavar="DIR")
    parser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False, help="verbosity of printouts")
    (options, args) = parser.parse_args()
    #print 'confold = ', options.confold
    #print 'workdir = ', options.workdir
    #print 'verbose = ', options.verbose

    global verbose
    verbose = options.verbose

    if options.workdir is None:
        CWD = os.getcwd()
    else:
        CWD = options.workdir

    global PROGTYPE, CONFTYPE
    if PROGTYPE != 'NARVAL':
        CONFTYPE = 'OFFLINE'
    if CONFTYPE == 'ONLINE':
        CWD = os.getcwd()

    for cc in ['$CONFDIR', '$READDIR', '$SAVEDIR']:
        if cc in MACROS:
            MACROS[cc] = os.path.join(CWD, MACROS[cc])  
    if CONFTYPE == 'ONLINE':
        MACROS['$SAVEDIR'] = MACROS['$READDIR']
        del MACROS['$READDIR']

    print
    print 'CWD     '.ljust(10), " --> ", CWD
    print 'PROGTYPE'.ljust(10), " --> ", PROGTYPE
    print 'CONFTYPE'.ljust(10), " --> ", CONFTYPE
    for a in MACROS:
        if MACROS[a] != '':
            print a.ljust(10), " --> ", MACROS[a]
    print

    newPrefix = MACROS['$CONFDIR']
    if options.confold is None:
        oldPrefix = ''
    else:
        oldPrefix = options.confold    
    return newPrefix, oldPrefix

def main():
    """
    """
    (newConf, oldConf) = checkArgsAndMacros()
    print "newConf = ", newConf
    print "oldConf = ", oldConf
    print

    global verbstr
    myGlobals = globals()

    for topo in Topology:
       block = Topology[topo]
       if isinstance(block, dict):
           dire = block.split()
       else:
           dire = block;
       for dd in dire.split():
            checkMakeDirs(dd)
            if topo in Actors:
                 print dd+'/'
                 verbstr = ""
                 actor = Actors[topo].split()
                 for aa in actor:
                     ff = makeFileName(newConf, dd, aa, topo)
                     printActor(myGlobals[aa], dd, ff)
                 if topo in ExtraFiles:
                     checkExtraFiles(newConf, oldConf, dd, ExtraFiles[topo])
                 if verbstr:
                     print " " + verbstr 

###############################################################################################
###############################################################################################

if __name__ == "__main__":
    main()
